import Head from 'next/head'
import styles from '../styles/App.module.css'
import Navbar from '../components/Navbar'
import Marketplace from '../components/Marketplace'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
        <Marketplace/>
      </main>
    </div>
  )
}
